Table Techdata(tech,dataset)                                                                                                                             
*PARAMETER NAME              TECHDATA                                                                                                                    
*INDICIES                    Tech     Dataset                                                                                                            
*TYPE                        ROW      COLUMN                                                                                                             
                                                                                                                                                         
                                                                                                                                                         
                                                                                                                                                         
                                                                                                                                                         
                                                                                                                                                         
*                            %of X/h  X/h              %load/h  %x         %x           x hours    x hours       euro/ x                                 
                             Minimum  Capacity         RampRate CapacityUP CapacityDown StorageCap InitialVolume VariableOmcost StartupCost              
WindTurbine                           54.6                                                                       0                                       
SolarPV                               27                                                                         0                                       
Electrolysis_1               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_2               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_3               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_4               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_5               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_6               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_7               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_8               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_9               0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_10              0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_11              0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_12              0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_13              0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_14              0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_15              0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_16              0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_17              0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_12_1            0.2      0.107            0.9      0.1        0.1                                   0              0                        
Electrolysis_12_2            0.2      0.107            0.9      0.1        0.1                                   0              0                        
ElectricStorage                       1.6                                               1.6        1             0.08                                    
MethanolSynthesis                     1.25                                                                       35             0                        
HydrogenCompressor                    1.926                                                                                                              
HydrogenStorage                       1.926                     0.1        0.1          7          3.5           0.05                                    
Digester                              3943.54503943545                                                                                                   
BiogasUpgrade                         2168.9497716895                                                                                                    
SplitterElectrolyser                  4.25914                                                                                                            
HEX1                                  0.36491                                                                                                            
HEX2                                  2.5116                                                                                                             
HEX3                                  0.61062                                                                                                            
Boiler1                               0.36491                                                                                                            
Boiler2                               2.5116                                                                                                             
Boiler3                               0.61062                                                                                                            
Boiler4                               0.31237                                                                                                            
HP1                                   39.622                                                                                                             
HEX4                                  8.8032                                                                                                             
HP2_W                                 1.02                                                                                                               
HP2_S                                 0.8644                                                                                                             
HP3_W                                 0.6253                                                                                                             
HP3_S                                 0.53                                                                                                               
HP4                                   1.567                                                                                                              
HEX5                                  0.34831                                                                                                            
