Table Techdata(tech,dataset)                                                                                                               
*PARAMETER NAME              TECHDATA                                                                                                      
*INDICIES                    Tech     Dataset                                                                                              
*TYPE                        ROW      COLUMN                                                                                               
                                                                                                                                           
                                                                                                                                           
                                                                                                                                           
                                                                                                                                           
                                                                                                                                           
*                            %of X/h  X/h              %load/h  %x         %x           x hours    x hours       euro/ x                   
                             Minimum  Capacity         RampRate CapacityUP CapacityDown StorageCap InitialVolume VariableOmcost StartupCost
WindTurbine                           54.6                                                                       0                         
SolarPV                               27                                                                         0                         
Electrolysis_12_1            0.2      0.107            0.9      0.1        0.1                                   0              0          
Electrolysis_12_2            0.2      0.107            0.9      0.1        0.1                                   0              0          
ElectricStorage                       1.6                                               1.6        1             0.08                      
MethanolSynthesis                     1.25                                                                       35             0          
HydrogenCompressor                    0.107                                                                                                
HydrogenStorage                       0.107                     0.1        0.1          7          3.5           0.05                      
Digester                              3943.54503943545                                                                                     
BiogasUpgrade                         2168.9497716895                                                                                      
Boiler1                               0.36491                                                                                              
Boiler2                               2.5116                                                                                               
Boiler3                               0.61062                                                                                              
Boiler4                               0.31237                                                                                              
